### ISSUE TITLE
[Feature] Mobile application

### ISSUE THREAD

**Issue by maltsavkiryl** [stamhoofd/stamhoofd#100]
Hey Simon, 

If I'm not mistaken, you were planning to provide a mobile application for stamhoofd. If so, I would definitely recommend to look into using flutter. It's a easy to use framework with a similar programming style/structure like react. 

Flutter is also compiled to native code and works out-of-the-box for Android and iOS. Performance is great and it's much easier to develop with than android/ios imho. 

There is a learning curve, but once you get a good architecture it's really easy to implement features. There are also build tools for deploying everything automatically.

Another benefit is that it's a growing community, completely open source and like it or not -> backed by Google :p

**Comment by WardToulet** [comment]
I thought the plan was to provided  a service worker and manifest to the application to turn it into a progressive web app this would allow the web app to function as a mobile app (on android at least, IOS does not support PWA's all that well) without splitting the effort between a flutter and a web frontend, thus slowing down development.

**Comment by SimonBackx** [comment]
Well, the plan was is to use [Capacitor](https://capacitorjs.com). The code is already optimized to run in an app like way and the usage of HTML and JS shouldn't be too noticeble in this type of application. Native apps or Flutter (although not such a fan of Flutter) is for the long term when we do have more developer capacity / bigger community (because everything needs to be rebuild since most logic runs in the frontend due to the end-to-end encyption).

The nice thing is that we can keep shipping new features at the same speed and that we can integrate the current registration process also in the app without duplicating any code.

Of cource, a native app will always feel better and be more responsive, but this is just a tradeoff we have to make to push the project further. If executing is good and we do optimize for performance, we can really hide the fact that is not an native app for most users.

But the app is very high on the todo list, I want to ship a basic version at least before the first of July.

**Comment by maltsavkiryl** [comment]
When focussing on business value, starting with a PWA or something like capacitor would definitely would be a better approach atm. Stamhoofd isn't an application that would benefit much from being native (at the moment).

**Comment by SimonBackx** [comment]
![IMG_B8D9CC3D550B-1](https://user-images.githubusercontent.com/5277847/123491818-f81a5800-d617-11eb-9ce2-cb7124dfbae2.jpeg)
![Screenshot_20210626-004609](https://user-images.githubusercontent.com/5277847/123491861-184a1700-d618-11eb-9b24-486ed44cac89.png)
We'll probably release open test versions of the app next week 🤞

**Comment by SimonBackx** [comment]
Apps will launch this week normally
