### ISSUE TITLE
Groups that aren't linked to price

### ISSUE THREAD

**Issue by nealjoos** [stamhoofd/stamhoofd#44]
Some organizations might want to have the possibility to create groups that aren't linked to the price (pure for organizational purposes).

For example: an organization has a price for members older than 16 years old (100 EUR) en one for younger members (50 EUR).
The price should be selected automatically, based on age, and the member should automatically join the corresponding group (adults or youth).
But they also have different groups based on the level of the member. (Let's take starter, experienced and expert as example).

So members should have a choice to join one of these level-based groups, but the price should be selected automatically based on age.

A feature like this would be amazing because groups like this are often used in sport clubs.

**Comment by SimonBackx** [comment]
This is a quite complex feature, hence the low priority. We need to think through how this will get implemented because this might have a big impact on the implementation of other future features.

Some possibilities:
- We'll build a feature to ask custom questions during registrations. This is a high priority feature, but we can include price changes in this feature to help solve this issue.
- Make the current pricing of a group more complex. But I feel this is not a good idea, we already have infinite price possibilities to family and number of registrations discount + reduced prices. There is no way we can combine all these possibilities without reworking the whole UI again.
