### ISSUE TITLE
More general registration page

### ISSUE THREAD

**Issue by WardToulet** [stamhoofd/stamhoofd#79]
Instead of having to select a group which requires parents or new members to know the structure of the group allow for a general registration page that just asks basic info (such as age) and then adds the member to the correct group.

We could also not add the user to a group directly after registration but add them to a staging area/waiting list as suggested in #58.

This could also have the benefit that parents/members of potential new members wouldn't directly have to make an account. They would just leave there email. And if the registration is accepted the would get an email allowing them to make an account.

**Comment by SimonBackx** [comment]
When you create a new member at the moment, it will automatically recommend all the possible groups. So that is already the case. For existing members you can also see all the 'matching' groups when clicking on the member -> register. So I don't really understand your idea. Could you explain it a bit more?

I'm not a fan of letting people register without an account, because we need an account (or key) in order to be able to encrypt all the member details. So when they receive the mail to create an account, they won't have access to that key and need to reenter all infromation again (or wait for a key share/verification via the dashbaord of the organization).

**Comment by SimonBackx** [comment]
@WardToulet Closed for now, if you have an addition we can always reopen this isssue
