### ISSUE TITLE
[Feature] Ticket sale

### ISSUE THREAD

**Issue by maltsavkiryl** [stamhoofd/stamhoofd#97]
Hey guys! What is the current status of the ticketsale module? That's something I would love to join and help on the analysis/development/design/... 

The selling of the tickets would be pretty use to implement by reusing the existing webshop module. It seems to fit pretty closely to how existing ticket sale software like eventsquare do. I have used eventsquare in the past and it works really well. We could get some great inspiration and lend some ideas on how they do it.

This could also be a big source of revenue depending on the monetization scheme. But there are also some risky aspects like paying back because of cancelation, servers slowing down because of traffic, holding the money ourselves or directly transferring the money to the host of the event, ...

**Comment by SimonBackx** [comment]
Yes, the tickets system will be included in the webshop package without additional fees or commissions. Somehow you should be able to set an individual product to 'Ticket' in a webshop which will automatically trigger the creation of PDF and iOS/Android wallet tickets with a QR-code that can be used at the event. The QR-code should contain some basic information with a digital signature to allow for offline verification of tickets (in case of internet failure). We could build the scanner into the coming app. If multiple devices are scanning tickets, it would be recommended to use an internet connection because we need to keep track whether a ticket is already scanned or not (to prevent sharing tickets). For most events, either there is only one scanning device or there is an internet connection (slow connection will do). So it should work fine.

**Comment by maltsavkiryl** [comment]
When you think about organising an event (like a party), you usually want to sell tickets (multiple types -> regular, earlybird, ...). But it would definitely be useful to sell drink vouchers in the same webshop. The customers proceeds the same flow as a regular webshop by confirming his order and paying. After the payment is settled, the ticket (and vouchers?) will be automatically sent to the customers email + pdf attached.

When creating a new article in the webshop, there could be an option to choose the "type" of article you want to sell. 
- ticket
- product
- service?
- ...
Depending on the type of article you have selected, you need to pass different kind of information for creating that "article".
 
When the webshop notices that you allow the selling of tickets, it shows an extra page where you can managing the ticket sales (number of tickets sold, remaining number of tickets, ... )
